version: "3.7"

services: 
  database_helpdesk:
    image: postgres
    container_name: database_helpdesk
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes: 
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: helpdesk
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - database_helpdesk
    depends_on: 
      - database_helpdesk

volumes:
  pgdata: 
    driver: local